### ISSUE TITLE
new 1.29 atom doesn't work on RHEL7.6 beta

### ISSUE THREAD

**Issue by vbenes** [flathub/io.atom.Atom#18]
after updating to 1.29 I see an error:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/app/share/atom/resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/app/share/atom/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

It wasn't the case with previous flatpak
sudo flatpak update --commit=d45cf3ff79f0143435aa5baf21c0c72e01d6c05e980a8c01250f66255357e355 io.atom.Atom

downgrading via above command solves the problem

**Comment by TingPing** [comment]
Does `flatpak run io.atom.Atom --safe` work?

**Comment by vbenes** [comment]
no
